### ISSUE TITLE
Cannot run train.py

### ISSUE THREAD

**Issue by arkadyark** [wdimmy/Confusionset-guided-Pointer-Networks-for-Chinese-Spelling-Check#2]
I am trying to run the `train.py` script, but I do not have the pertained embeddings file `zhwiki.lsn.char`. Where can I get this?

**Comment by wdimmy** [comment]
Hi，zhwiki.lsn.char is a  **char-level** Chinese embedding, which was pretrained by us, and sorry we are not going to share it.  You can download any pretrained char-level embedding available on the Internet or use a randomly initialized embedding matrix.
